version: '3.9'
services:
  backend:
    image: bajetibuddy/backend:latest # TODO: set actual image registry/tag
    env_file:
      - ../backend/.env
    volumes:
      - ../backend/data:/usr/src/app/data
    ports:
      - "3000:3000"
  mobile_web:
    image: bajetibuddy/mobile_web:latest # TODO: set actual image registry/tag
    depends_on:
      - backend
    ports:
      - "8080:80"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mobile_web
      - backend
    ports:
      - "80:80"
      - "443:443"
