name: bajeti_buddy
version: 0.1.0
description: A simple budgeting app

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  firebase_core: ^2.32.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - Assets.xcassets/
    - ../../web/icons/
    - ../assets/icons/
    - ../assets/images/
