name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Build
        run: npm run build
        working-directory: backend

      - name: Run tests
        run: npm test
        working-directory: backend

      - name: Docker login
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          # TODO: set registry token secret
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/myorg/bajetibuddy-backend:latest ./backend
          docker push ghcr.io/myorg/bajetibuddy-backend:latest
